
name: Build and Deploy Angular App to AWS S3
on:
  push:
    branches:
      - master
      - main
jobs:
  build-and-deploy:
    name: Buiild and Deploy
    runs-on: ubuntu-latest
    env:
      bucket-name: backops-frontend
      region: ap-south-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install AWS CLI and configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.region }}
      - name: Install dependencies
        run: |
          node --version
          ls -all
          npm ci
      - name: Build Angular App
        run: |
          npm run build
      - name: Upload the generate files to S3 bucket
        run: |
          aws s3 sync --delete ./dist/backop-frontend/browser s3://${{ env.bucket-name }}
